# Generated by Django 4.0.1 on 2022-02-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0002_salaryemployers_alter_reestrusers_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agregat',
            fields=[
                ('agregat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_agr', models.TextField(blank=True, null=True)),
                ('serial_num', models.TextField(blank=True, null=True)),
                ('current_quality', models.TextField(blank=True, null=True)),
                ('data_production', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agregat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsA',
            fields=[
                ('producta_no', models.IntegerField(primary_key=True, serialize=False)),
                ('namea', models.TextField(blank=True, null=True)),
                ('batch_numa', models.IntegerField(blank=True, null=True)),
                ('data_prod_a', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products_a',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsB',
            fields=[
                ('productb_no', models.IntegerField(primary_key=True, serialize=False)),
                ('nameb', models.TextField(blank=True, null=True)),
                ('batch_numb', models.IntegerField(blank=True, null=True)),
                ('data_prod_b', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products_b',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Document2',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='ReestrUsers',
        ),
        migrations.DeleteModel(
            name='SalaryEmployers',
        ),
    ]
